name: Diary Api
on: push

jobs:
  test_api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install pipenv
        run: |
          pip3 install --upgrade pip
          pip3 install pipenv

      - name: Install dependencies
        run: |
          pipenv install --dev
      
      - name: confirm installes dependencies
        run: |
          pipenv run pip3 freeze
      - name: move into project dirctory
        run: |
          cd dairyapp
      - name: make migration
        run: |
          pipenv run python3 manage.py makemigrations diary
          pipenv run python3 manage.py migrate
      - name: Run test
        run: |
          pipenv run python3 manage.py test

